# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate:    10 # pagination basted on number of posts
exclude:     ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', '.gitignore', 'ruby-version', 'deploy.sh', 'nginx.conf', 'Procfile'] # files to exclude
highlighter: pygments
markdown:    redcarpet
gems:
  - jekyll-paginate
